### ISSUE TITLE
[WIP] Issue / Pull Request Automation

### ISSUE THREAD

**Issue by joshwiens** [webpack-contrib/organization#6] opened 2017-02-26 07:29 UTC
**Proposal By:** @bebraw @d3viant0ne

**Scope:** All repositories in `webpack-contrib` 

## Motivation / Use Case

We have more issues than we have time. Given the nature of `webpack-contrib` and the desire to bring more loaders / plugins into the fold, human maintenance of 43+ repositories doesn't scale. At best it's a time sink and at worst, the end user suffers when issues slip through the cracks and pull request rot.

The simple reality is there will always be a small group doing a large portion of the maintenance.  Given the tedious and time consuming nature of issue & pull request management, we need to implement a level of automation. 

**_Regardless of good intentions human contributions will always ebb and flow, this is not a problem we can solve by simply throwing bodies at it._**

## Implementation

_**Modify a fork of https://github.com/babel/babel-bot to fit our issue & pull request needs while incorporating features from eslint's / k8 bot**_

There is discussion around a general OSS bot. While the benefits are clear, trying to balance features / requirements with a general use bot in our case would probably be more trouble than it's worth. We also need this sooner than later, waiting for something that doesn't exist isn't viable. 

A `cooperative effort with Babel may be a viable option` but agreeing on features / requirements will always be an issue. No two orgs are going to maintain their projects the same way, we can't even manage that between `webpack` & `webpack-contrib`. Getting orgs to conform to a single way of maintaining projects to apply a purpose built bot just isn't realistic.

`Perhaps the right answer here is creating an extensible base bot` ( rule based? pluggable? ) as a cooperative effort allowing orgs to customize and extend to fit their needs. As it stands, I maintain a non-trival collection of AWS Lambda functions so I know it's viable to call a Lambda based on condition inside the parent and pass in a payload. This could be a possible high level path to creating a pluggable, Lambda based bot. //cc @hzoo

That approach does have it's flaws. Given that AWS Lambda functions are billed every time it is called, triggering B from A means each execution pass of a plugin requires two function calls ( at least ). AWS is liberal with it's billing for Lambda functions, so there is no expectation of the cost increase being exorbitant  but it should be highlighted as a know concern.

Issue & pr automation requires walking a `fine line` between beneficial and detrimental to both users and maintainers ( Sails issue bot is a good example of this ). Babel's implementation does an excellent job walking that line thus far.

## Requirements [WIP]

**Before any real effort is put into requirements discussion, we need to decide if this is going to be a `Babel / Webpack effort` or if we are going to fork and go our own direction. Duplication of effort is never a good thing, if Babel & Webpack can come up with a pluggable maintenance bot it's beneficial to any org on github.**

#### Issues

- Identify & tag new issues not yet triaged for easy visibility 
- Check issues for basic metadata requirements 
- Tag issue as `ready for triage` only after basic requirements have been met. This should be communicated via issue comment after X amount of time. ( hours / day ? ) if it doesn't exist.
- Close issues if `response required` from user for more than 30 days and reopen if the creator responds.
- Issues closed by a pull request should be locked? Comments on old issues is the easiest way for an issue to slip through the cracks.

#### Pull Requests

- Validate commit message format, comment with instructions for malformed commit messages.
- Adds a default label after PR criteria is met ( needs to be defined ).
- Slack integration to purpose created channel for pull requests older than X days not yet reviewed notifying admin team.

## Infrastructure

- Requires an `AWS` account for the org and `IAM configuration` for approved users.
- At least 2 Lambda functions ( Bot plus Slack )
- API Gateway
- Requires `github user` for the bot
- Need to get an estimate on operational cost if approved. Henry should be able to give us some idea on the monthly cost.

**Comment by michael-ciniawsky** [comment] 2017-02-26 10:33
### Motivation

Full ACK 👍

### Implementations

> We can't even manage that between webpack & webpack-contrib

Why... ? Seriously 😛 It can't be that difficult, if both sides want/see it as required/benefical, which is a discussion on it's own. Code Style/CI && Coverage Setup should be aligned, unless changes are not required for specifics. To babel or not to babel is a temporarily question.

A generic Github Bot as a new OSS project, which is plugable/extendable/reusable by whomever, should be the way to go :D. Candidates to for getting started/inspired are babel-, node-, eslint-bot. There would also be room for future projects e.g Github [Bot] CLI, Core Plugins etc. unified under the same umbrella and maybe get some fundings, if it attracts enough interest 💯. 

### Issues 

> Check issues for basic metadata requirements

👍  and please immediately close Issues not following the `ISSUE_TEMPLATE`. The template shouldn't be too complicated/time consuming, but simply ignoring it and trying to get along with it, which basically means shifting the mental overhead of getting a grasp about the problem to others === Close ❌ 

> Close issues if response required from user for more than 30 days and reopen if the creator responds.

I'm in favour of Issue 'closing windows' based on certain categories expressed through labels with e.g `stackoverflow, usage, etc...` => 5, 10, etc...

> Issues closed by a pull request should be locked? Comments on old issues is the easiest way for an issue to slip through the cracks.

? 🤔...  Until the PR fixing the related Issue is merged and released? Otherwise, if no additional `bug` label etc. is added, time is running again 🔪 

### Pull Requests

> Adds a default label after PR criteria is met ( needs to be defined ).

A while ago I stepped over a nice PR Workflow (I think it was Docker), which has these 4 stages 

##### Status

0. Triage  (Proposal)
1.  Design (Feedback, Architecture, Logic, ... Issues)
2.  Code   (Style && Test Issues)
3.  Docs   (Documenation Issues)
4.  Merge (Milestone/Release x.x.x)

##### MAINTAINERS

There (sadly) **was** a service called [LTGM](https://github.com/lgtmco/lgtm), which worked by adding a `MAINTAINERS` file and folks listed there simply commented with `LGTM` on a PR and at a certain threshold of `LGTM`'s it gets merged automatically (Core Plugin Idea for Gihub Bot 🤗).

**Comment by joshwiens** [comment] 2017-02-26 15:44
@michael-ciniawsky - `and please immediately close Issues not following the ISSUE_TEMPLATE` while I agree here personally, we should probably have the bot comment on issues not following the template and give the creator time to correct the issue as opposed to immediately closing it.

Perhaps a more forgiving workflow ..

_On Issue is creation_
- Bot checks metadata & applies a default label or comments on issue citing deficiencies. 
- Any issue not updated to the proper standards is closed automatically the following day? X hours?

_On our end_
- If an issue doesn't have at minimum a default label, it is ignored entirely.
- Worst case, the malformed clutter is cleaned out the following day.

**Comment by michael-ciniawsky** [comment] 2017-02-26 16:18
@d3viant0ne Yep the bot sends a notifaction and reopens when the issuer has updated the template and like mentioned before the `ISSUE_TEMPALTE` shouldn't be a doctoral thesis to write 😛 

> Perhaps a more forgiving workflow ..

Sure, the mentioned workflow is only a 'inspiraton' and PR for projects like docker tend to have a far more higher complexity as for webpack loaders 
> Bot checks metadata & applies a default label or comments on issue citing deficiencies.

👍 

> Any issue not updated to the proper standards is closed automatically the following day? X hours?

Maybe 2-3 days in case someone is busy with work etc, but a definitely a short window 

> If an issue doesn't have at minimum a default label, it is ignored entirely

If the template is filled correctly (metadata) and no tags other then a 'default' label are added automatically (bot), the standard procedure could be e.g tag as  'question'  and close within 5-10 days, if not relabeled manually because of e.g a confirmed bug etc.

> Worst case, the malformed clutter is cleaned out the following day.

👍

**Closed as completed** 2017-03-02 19:35 UTC
Labels: RFC/Proposal, Status: Pending
