### ISSUE TITLE
[WIP] RFC: Merge & Release Automation

### ISSUE THREAD

**Issue by joshwiens** [webpack-contrib/organization#2] opened 2017-01-26 23:15 UTC
## Webpack-Contrib Continuous Delivery 

Per @TheLarkInn we will be implementing a full `continuous delivery` workflow for all libraries under `webpack-contrib` allowing the contrib team to focus on reviews & features not publishing. It also has the added benefit of getting our released features and fixes out to the public faster.

The system will operate outside the normal TravisCI continuous integration on a cron driven build pipeline where any open pull requests flagged as ready for merge will be validated and merged automatically.

A cron based release pipeline will validate, update the changelog, tag & publish the changes in master. My initial feeling is weekly or bi-weekly publishing as nightly or immediate would feel too spammy to the end user ( think of the greenkeeper.io spam ). The timing is open for discussion.

A nightly/weekly `@next` build for some / all libraries is also a possibility though it should probably be reserved for those plugins & loaders with higher contribution levels so we aren't burning CPU time pushing `@next` tags for plugins & loaders in more of a maintenance mode.

_Requirements_

- End to end automation of a release once an PR has been flagged for merge.
  - standard-version updates the changelog and cuts the tag
  - use github api to update the release notes on the tag with the changelog
  - runs the `dist:build` and published the tag to npm
  - notifies greenkeeper & slack
- System will release any commit in master with type `fix` or `feat` when the pipeline runs
  - allows for manual release without side effects to the automation pipeline
  - commits with types other than `fix || feat` with be included in the next release having a releasable code change.
- Libraries that warrant it will also publish `@next` tags using the same release flow at a higher frequency. 

### Merge & Release Standards

Commit messages will follow the [Angular commit message format](https://gist.github.com/d3viant0ne/dd16e98cfa3ba1ca09d67714dbdcb123)
Standard Version will be used for to generate changelog & github tags

_Release Documentation_
https://webpack.js.org/development/release-process/

- [ ] Add `standard-version` to all `webpack-contrib` repos.
- [ ] Reword history for all contrib repos for the current major version.

### Change Validation Standards

_TBD_

### Release Automation Implementation

- [ ] Define mechanism to promote pull requests ready for release automation
- [ ] CI / CD infrastructure. 
- [ ] CI implementation for automated PR merge.
- [ ] CD implementation for production build & npm publishing of minor & patch versions.
- [ ] CD implementation for npm publishing of major versions.
- [ ] CD implementation for writing release notes to the newly created github tag.
- [ ] CD implementation to publish `@next` tags for candidate libraries.

Is Blocked By #1 

>This is a draft with many areas needing to be fleshed out, information can and will change.

**Comment by michael-ciniawsky** [comment] 2017-01-27 21:29
Close Issues tagged as e.g question/usage after a certain time to keep the issue tracker clean. VS Code is doing that, closing issues which are not a bug or feature request etc after ~10 days. 10 is maybe a bit rough but within a month I think it's justifiable.

**Comment by TheLarkInn** [comment] 2017-01-27 22:50
I'm fine with 10-14 Days. That is what eslint and vue do.

**Closed as completed** 2017-01-30 19:45 UTC
